# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"

  # Disable automatic box update checking. If you disable this, then
  # boxes will only be checked for updates when the user runs
  # `vagrant box outdated`. This is not recommended.
  config.vm.box_check_update = false

  config.ssh.forward_x11 = true

  config.vm.synced_folder "/home/makism/Dropbox/Temp/pyspark/agile/", "/agile/"
  config.vm.synced_folder "/home/makism/Dropbox/mtgp/", "/mtgp/"

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine. In the example below,
  # accessing "localhost:8080" will access port 80 on the guest machine.
  # NOTE: This will enable public access to the opened port

  # Spark
  config.vm.network :forwarded_port, guest: 8888, host: 8888#, host_ip: "127.0.0.1"
  config.vm.network :forwarded_port, guest: 4040, host: 4040#, auto_correct: true
  config.vm.network :forwarded_port, guest: 4041, host: 4041#, auto_correct: true

  # Kafka
  config.vm.network :forwarded_port, guest: 9092, host: 9092#, host_ip: "127.0.0.1"
  # Zookeeper
  config.vm.network :forwarded_port, guest: 2181, host: 2181

  # Zeppelin
  config.vm.network :forwarded_port, guest: 9999, host: 9999

  # Hadoop
  config.vm.network :forwarded_port, guest: 9879, host: 9870
  config.vm.network :forwarded_port, guest: 8042, host: 8042
  config.vm.network :forwarded_port, guest: 9864, host: 9864

  # Mongo
  config.vm.network :forwarded_port, guest: 27017, host: 27017

  # Elasticsearch
  config.vm.network :forwarded_port, guest: 9200, host: 9200

  # Flask
  config.vm.network :forwarded_port, guest: 5000, host: 5000

  # Create a forwarded port mapping which allows access to a specific port
  # within the machine from a port on the host machine and only allow access
  # via 127.0.0.1 to disable public access
  # config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # config.vm.network "private_network", ip: "192.168.33.10"

  # Create a public network, which generally matched to bridged network.
  # Bridged networks make the machine appear as another physical device on
  # your network.
  # config.vm.network "public_network"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder "../data", "/vagrant_data"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.
  # Example for VirtualBox:
  #
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "spark"
    vb.cpus = 2
    vb.memory = "4098"
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
  end
  #
  # View the documentation for the provider you are using for more
  # information on available options.

  # Enable provisioning with a shell script. Additional provisioners such as
  # Puppet, Chef, Ansible, Salt, and Docker are also available. Please see the
  # documentation for more information about their specific syntax and use.
  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL
  config.vm.provision :shell, :path => "bootstrap.sh"
end
